packages:
  - packages/*
  - tools/*
  - services/*
  - routes/*

overrides:
  '@mempool/mempool.js>axios': 1.12.2

ignoredBuiltDependencies:
  - '@sentry/cli'

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@swc/core'
  - core-js
  - esbuild
  - msw
  - nx
  - protobufjs
  - secp256k1
  - sharp
  - unrs-resolver
