/**
 * Watchtower artifact assembly and verification through the real WASM, on a
 * graph-v1 (Vault Core 1) vault generated by btc-vault's own test recipe (see
 * `fixtures/watchtowerArtifacts/README.md`). The other delegated-claim tests
 * mock the WASM boundary, so this is the one place the SDK's reading of an
 * unjoined or joined `babe_sessions` map meets the Rust builder and verifier.
 */

import { readFileSync } from "node:fs";

import type { WatchtowerArtifactsInputs } from "@babylonlabs-io/babylon-tbv-rust-wasm";
import { describe, expect, it } from "vitest";

import { buildWatchtowerArtifacts } from "../../../wasm";
import { assertArtifactsUsableForVault } from "../readWatchtowerArtifacts";
import { UNJOINED_BABE_SESSIONS_JSON } from "../types";

interface WatchtowerArtifactsFixture {
  inputs: Omit<WatchtowerArtifactsInputs, "claimableEventBlockNumber"> & {
    claimableEventBlockNumber: number;
  };
  babeSessionsJoined: Record<string, { decryptor_artifacts_hex: string }>;
  usableForVault: {
    expectedVaultId: string;
    depositorEthAddress: string;
    trustedVerifyingKeyHex: string;
    expectedProverCircuitVersion: number;
    expectedClaimableEventBlockNumber: number;
  };
  vault: { challengerPubkeys: string[]; depositorBtcXOnlyPubkey: string };
}

const fixture = JSON.parse(
  readFileSync(
    new URL("./fixtures/watchtowerArtifacts/fixture.json", import.meta.url),
    "utf8",
  ),
) as WatchtowerArtifactsFixture;

function inputsWith(babeSessionsJson: string): WatchtowerArtifactsInputs {
  return {
    ...fixture.inputs,
    claimableEventBlockNumber: BigInt(fixture.inputs.claimableEventBlockNumber),
    babeSessionsJson,
  };
}

function assertUsable(artifactsJson: string) {
  const usable = fixture.usableForVault;
  return assertArtifactsUsableForVault({
    artifactsJson,
    expectedVaultId: usable.expectedVaultId,
    depositorEthAddress: usable.depositorEthAddress,
    trustedVerifyingKeyHex: usable.trustedVerifyingKeyHex,
    expectedProverCircuitVersion: usable.expectedProverCircuitVersion,
    expectedClaimableEventBlockNumber: BigInt(
      usable.expectedClaimableEventBlockNumber,
    ),
  });
}

describe("watchtower artifacts through the real WASM (graph v1)", () => {
  it("builds an unjoined file that verifies and reads as unjoined", async () => {
    const artifactsJson = await buildWatchtowerArtifacts(
      inputsWith(UNJOINED_BABE_SESSIONS_JSON),
    );

    expect(JSON.parse(artifactsJson).babe_sessions).toEqual({});
    const summary = await assertUsable(artifactsJson);
    expect(summary.babeSessions).toEqual({ joined: false });
  });

  it("builds a joined file that verifies and lists every challenger", async () => {
    const artifactsJson = await buildWatchtowerArtifacts(
      inputsWith(JSON.stringify(fixture.babeSessionsJoined)),
    );

    const summary = await assertUsable(artifactsJson);
    expect(summary.babeSessions.joined).toBe(true);
    expect(
      summary.babeSessions.joined
        ? [...summary.babeSessions.challengerPubkeys].sort()
        : [],
    ).toEqual(fixture.vault.challengerPubkeys);
  });

  it("refuses a session map missing one of the graph's challengers", async () => {
    const [dropped, ...kept] = fixture.vault.challengerPubkeys;
    const partial = Object.fromEntries(
      kept.map((pubkey) => [pubkey, fixture.babeSessionsJoined[pubkey]]),
    );

    await expect(
      buildWatchtowerArtifacts(inputsWith(JSON.stringify(partial))),
    ).rejects.toThrow(`babe_sessions has no entry for graph challenger ${dropped}`);
  });

  it("refuses a session map keyed by a key that is not a graph challenger", async () => {
    // A valid x-only key, so the refusal is the coverage check and not a
    // key-parse failure.
    const foreign = fixture.vault.depositorBtcXOnlyPubkey;
    expect(fixture.vault.challengerPubkeys).not.toContain(foreign);
    const sessions = {
      ...fixture.babeSessionsJoined,
      [foreign]: { decryptor_artifacts_hex: "a1a2" },
    };

    await expect(
      buildWatchtowerArtifacts(inputsWith(JSON.stringify(sessions))),
    ).rejects.toThrow(/not a graph challenger/);
  });

  it("refuses an unjoined file whose claimer signature does not verify", async () => {
    const sig = fixture.inputs.assertClaimerSigHex;
    const corrupted = `${sig.slice(0, -2)}${sig.endsWith("00") ? "01" : "00"}`;

    await expect(
      buildWatchtowerArtifacts({
        ...inputsWith(UNJOINED_BABE_SESSIONS_JSON),
        assertClaimerSigHex: corrupted,
      }),
    ).rejects.toThrow(/assert_claimer_sig does not verify/);
  });
});
