name: BSN Registry Validate

on:
  pull_request:
    paths:
      - 'packages/babylon-bsn-registry/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'

      - name: Install Corepack
        run: npm install -g corepack && corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate BSN registry icons and URLs
        run: pnpm --filter babylon-bsn-registry run validate-images
