name: Build and Release in Mono Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'

      - name: Install dependencies
        run: npm install

      - name: Single Version Policy
        run: |-
          # Exit immediately if any command in the script fails
          set -e

          if npx syncpack list-mismatches; then
            echo "✅ Dependency versions are aligned"
          else
            # Add an annotation to the Checks tab with a helpful hint
            echo "::error title=Dependency mismatch::Run 'npx syncpack list-mismatches' locally (and 'npx syncpack fix-mismatches' to auto-fix)." >&2
            exit 1
          fi

      - name: Lint all
        run: npx nx run-many --target=lint --all

      - name: Test all
        run: npx nx run-many --target=test --all

      - name: Build all
        run: npx nx run-many --target=build --all

      - name: Release changed packages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}