name: Build and Release in Mono Repo

on:
  push:
    branches:
      - main
      - vault

jobs:
  build_and_release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Corepack
        run: npm install -g corepack && corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Single Version Policy
        run: |-
          # Exit immediately if any command in the script fails
          set -e

          if pnpm exec syncpack list-mismatches; then
            echo "✅ Dependency versions are aligned"
          else
            # Add an annotation to the Checks tab with a helpful hint
            echo "::error title=Dependency mismatch::Run 'pnpm exec syncpack list-mismatches' locally (and 'pnpm exec syncpack fix-mismatches' to auto-fix)." >&2
            exit 1
          fi

      - name: Build all
        run: pnpm exec nx run-many --target=build --all

      - name: Lint all
        run: pnpm exec nx run-many --target=lint --all

      - name: Test all
        run: pnpm exec nx run-many --target=test --all



      - name: Release changed packages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          pnpm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}