name: Build and Release in Mono Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install

      - name: Lint all
        run: npx nx run-many --target=lint --all

      - name: Test all
        run: npx nx run-many --target=test --all

      - name: Build all
        run: npx nx run-many --target=build --all

      - name: Release changed packages
        run: npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}