name: Verify PR

on:
  pull_request:
    branches: [main] # or your default branch

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4 https://github.com/actions/setup-node/releases/tag/v4
        with:
          node-version: '24.2.0'

      - name: Install Corepack
        run: npm install -g corepack && corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Single Version Policy
        run: |-
          # Exit immediately if any command in the script fails
          set -e

          if pnpm exec syncpack list-mismatches; then
            echo "✅ Dependency versions are aligned"
          else
            # Add an annotation to the Checks tab with a helpful hint
            echo "::error title=Dependency mismatch::Run 'pnpm exec syncpack list-mismatches' locally (and 'pnpm exec syncpack fix-mismatches' to auto-fix)." >&2
            exit 1
          fi

      - name: Build all
        run: pnpm build

      - name: Lint all
        run: pnpm run lint

      - name: Test affected
        run: pnpm exec nx affected --target=test --base=origin/main --verbose

      - name: Validate TypeDoc
        run: |
          cd packages/babylon-ts-sdk
          pnpm docs:validate
